AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  # DYNAMO DB
  DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: todos

  # API GATEWAY
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: swagger-output.yaml
      StageName: Prod
      Variables:
        CreateLambda: !Ref Create
        DeleteLambda: !Ref Delete
        ListLambda: !Ref List
        UpdateLambda: !Ref Update

  # FUNCTIONS
  Create:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create.create
      CodeUri: ../src
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /todos
            RestApiId: !Ref ApiGatewayApi
            Method: POST

  Delete:
    Type: AWS::Serverless::Function
    Properties:
        Handler: delete.delete
        CodeUri: ../src
        Runtime: nodejs6.10
        Policies: AmazonDynamoDBFullAccess
        Environment:
          Variables:
            DYNAMODB_TABLE: !Ref DynamoDBTable
        Events:
          GetResource:
            Type: Api
            Properties:
              Path: /todos
              RestApiId: !Ref ApiGatewayApi
              Method: DELETE

  List:
    Type: AWS::Serverless::Function
    Properties:
      Handler: list.list
      CodeUri: ../src
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /todos
            RestApiId: !Ref ApiGatewayApi
            Method: GET

  Update:
    Type: AWS::Serverless::Function
    Properties:
      Handler: update.update
      CodeUri: ../src
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /todos
            RestApiId: !Ref ApiGatewayApi
            Method: PUT