AWSTemplateFormatVersion: '2010-09-09'

# From https://github.com/awslabs/aws-cloudformation-templates/commit/c6a76908bbebdfb453de876fde8052aaf1ebf4e7#diff-e41bf9f015f6ad5894d493c0779f9b53R16
Mappings:
  Region2S3WebsiteSuffix:
    eu-central-1:
      Suffix: .s3-website.eu-central-1.amazonaws.com

Parameters:
  DomainName:
    Type: String
    Description: The Domain
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description : HostedZoneId of the Domain
  AcmCertificateArn:
    Type: String
    Description: Arn of the corresponding Domain Certificate

### WebsiteBucket Resources

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      WebsiteConfiguration:
        ErrorDocument: 'index.html'
        IndexDocument: 'index.html'
  S3BucketPolicy: 
    Type: 'AWS::S3::BucketPolicy'
    Properties: 
      Bucket: 
        Ref: S3Bucket
      PolicyDocument: 
        Statement: 
          - Action: 
              - 's3:GetObject'
            Effect: Allow
            Principal: '*'
            Resource: !Join ['', ['arn:aws:s3:::', {Ref: S3Bucket}, '/*' ]]

### CloudFront Resources
  
  CloudFront:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: '/index.html'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Ref S3Bucket
          ViewerProtocolPolicy: 'redirect-to-https'
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !Join ['', [!Ref 'S3Bucket', !FindInMap [Region2S3WebsiteSuffix, !Ref 'AWS::Region', Suffix]]]
            Id: !Ref S3Bucket
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        # only needed if using custom domain
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only

# Custom Domain Resources

  Route53:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFront.DomainName
        EvaluateTargetHealth: false
        HostedZoneId: 'Z2FDTNDATAQYW2'
  

Outputs:
  S3BucketName:
    Description: The S3Bucket Name
    Value: !Ref S3Bucket
  S3BucketWebsiteURL:
    Description: The S3Bucket URL
    Value: !GetAtt S3Bucket.WebsiteURL
  CloudFrontDistributionId:
    Description: The CloudFront Distribution Id
    Value: !Ref CloudFront